### PR TITLE
fix(typo): server.xml section

### PR DESCRIPTION
**Pull request by laurentleseigneur**
* remove unexpected space
* adjust indent

### CODE REVIEW

**Comment by educhastenier** [comment]
Why from 7.9 only?

**Comment by laurentleseigneur** [comment]
it could be any version. which first one do you prefer?

**Comment by laurentleseigneur** [comment]
https://github.com/bonitasoft/bonita-doc/pull/816 is also impacted if we merge this in 7.6 or older

**Comment by educhastenier** [comment]
> it could be any version. which first one do you prefer?

7.6, for both PRs, as this is the oldest supported version.
Thx

**Comment by laurentleseigneur** [comment]
replaced by https://github.com/bonitasoft/bonita-doc/pull/824

**Pull request closed without merging**
