### PR TITLE
fix(wildfly) fix bonita-platform-init-community-custom.properties pat…

### PR DESCRIPTION
**Pull request by cpuy**
…h in wildfly bundle

### CODE REVIEW

**Comment by redboul** [comment]
This applies on jboss bundle of 7.3 too, can you open the PR on 7.3 instead plz ?

**Comment by cpuy** [comment]
Yep

**Comment by cpuy** [comment]
Will it be properly rebased ?

**Comment by cpuy** [comment]
To be reopened on 7.3

**Pull request closed without merging**
