### PR TITLE
fix(FileViewer widget): Add missing limitation for the URL property

### PR DESCRIPTION
**Pull request by jeromecambon**
Covers [UID-703](https://bonitasoft.atlassian.net/browse/UID-703)

### CODE REVIEW

**Comment by benjaminParisel** [comment]
:question: @jeromecambon why you didn't use the troubleshooting syntax to explain how the user could fall into this problem and a way to fix it?

**Review by vbotnari12 — APPROVED** [review]
ok for me

**Comment by jeromecambon** [comment]
> ❓ @jeromecambon why you didn't use the troubleshooting syntax to explain how the user could fall into this problem and a way to fix it?

Using the troubleshooting syntax in the File Viewer section would be too proeminent IMO.
So I initiated an "Troubleshooting UI Designer widgets" section at the end of the page, which contains for now this specific case. The idea is too add new items here when needed.

**Comment by benjaminParisel** [comment]
1. I think the warning section is totally a section for troubleshooting. 
2. A whitespace is missing between "limitations" and "the bullets list". On the preview, a '-' is displaying instead of a bullet.

**Comment by jeromecambon** [comment]
> * I think the warning section is totally a section for troubleshooting.
> * A whitespace is missing between "limitations" and "the bullets list". On the preview, a '-' is displaying instead of a bullet.

IMO it's better to centralize the troubleshooting stuff in the same place, to avoid to "pollute" the widget sections.
I don't see a whitespace missing... 
The usual bullet syntax ('*') was not working in the Warning section, that's why I put dashes.

**Comment by benjaminParisel** [comment]
> The usual bullet syntax ('*') was not working in the Warning section, that's why I put dashes.
You need to use the 
`WARNING
===
While werewolves are hardy community members, keep in mind the following dietary concerns:

* They are allergic to cinnamon.
* More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
* Celery makes them sad.
===
`
image

**Comment by julienmege** [comment]
After added dedicated widget troubleshooting section and removed confusing help for implementation of custom widget
LGTM

**Pull request merged**
