### PR TITLE
update(index): insert 7.12 main content

### PR DESCRIPTION
**Pull request by NathalieC**
* add 7.12 main values + anchors to the release notes

### CODE REVIEW

**Comment by educhastenier** [comment]
retest this please

**Review by educhastenier — CHANGES_REQUESTED** [review]
⚠️ Links to release notes don't work

**Comment by NathalieC** [comment]
@educhastenier the release notes was not merged. I merged it so you can test the index page now.

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
> @educhastenier the release notes was not merged. I merged it so you can test the index page now.

@NathalieC Links are still invalid. I think their name is incorrect in most cases.
I let you check that.

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
✔️ Ok once rebased onto 7.12

**Review by educhastenier — APPROVED** [review]

**Pull request merged**
