### PR TITLE
test: validate branch name compliance

### PR DESCRIPTION
**Pull request by vhemery**
### IMPORTANT NOTE

This PR is not intended to be merged as its content has already been merged in #2311.
It has been reopened to test the implementation of https://github.com/bonitasoft/bonita-documentation-site/pull/513
It will be closed once this issue is completed.

### Original purpose of this PR

The original name of this PR was `docs(release-notes): Update release note for 7.15.2`. It was closed because of the branch name of this PR caused issues.
The content of this PR was merged via #2311

### CODE REVIEW

**Comment by tbouffard** [comment]
✔️ the branch of this PR is detected as invalid by the "publish PR preview" workflow. Here is what we see in the summary of the workflow. The error message is also visible in the logs of the workflow run.
So the preview is not built nor published to surge.sh.
✔️ also detected by the "build PR preview" workflow

image

**Comment by vhemery** [comment]
@tbouffard Do we still need this opened are can we close it ?

**Comment by tbouffard** [comment]
Yes, we need it to finalize tests for https://github.com/bonitasoft/bonita-documentation-site/pull/513
I will close it once the issue implementation is completed.

I have updated the PR description and its title to clarify.

**Comment by tbouffard** [comment]
✔️ Tested with the actions of the latest commit of the bonita-documentation-site master branch (https://github.com/bonitasoft/bonita-documentation-site/commit/486a811a50fe6658a54e76cceb3475d0f663f450)

All tests are completed, so closing this issue.

**Pull request closed without merging**
