### PR TITLE
feat(SAML): integrate user test feedback

### PR DESCRIPTION
**Pull request by abirembaut**
- add IdP section
- add keys and certificates format note
- add explanation on how to test the login (URL)
- add logging configuration for troubleshooting

Covers [BS-16586](https://bonitasoft.atlassian.net/browse/BS-16586)

### CODE REVIEW

**Comment by NathalieC** [comment]
After Train the Trainers, a need has been raised to add a few sentences that explain:
- why logout has not been implemented (different behavior depending on the IdP)
- how to hide the logout button in Bonita

**Comment by PierrickVoulet** [comment]
[Here ](https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.0/html/securing_applications_and_services_guide/saml_2) is a complete doc for the keycloak (edited by RedHat, same as the one found on Keycloak but more readable).

The idea is to provide a minimal content removing all not mandatory parts (tags/attributes) in the default XML that define default behavior/value discussed in the RedHat documentation. I already did the exercise for a customer, it worked on the last RC without any issue.

**Comment by abirembaut** [comment]
@NathalieC 
- There is already a clear explanation of the procedure to hide the logout button.
- As for single logout, all IdP do not support global logout and  there are different Single logout mechanism. But the real reason why we do not support it is that we didn't identified it as a common use case we need to support. Most existing customers are satisfied with hiding the logout button. I understand that it is not suitable for public computers, though. We could investigate more on the topic if it becomes a use case we need to support natively. Currently, you can implement your authentication Manager extending the SAML one to override the logout method. Should we say that in the doc ?

@PierrickVouletBonitasoft 
Thanks. we will create a new jira issue to remove the default attributes that should never be modified

**Comment by NathalieC** [comment]
The updated page can also point to a blog post from @lio-p, based on this page, that explains how to setup SAML with SalesForce. It can be found here (for now): https://docs.google.com/document/d/1Bn3p6gFFqV7AkIzjkm5eSYRtpVAyYVwIeQmJLhI13ms/edit
@lio-p : could you send us the final location when it's published?

**Comment by abirembaut** [comment]
IMHO, this should be handled in another PR and we should merge this one ASAP to help people trying to setup SAML with 7.5.

**Comment by abirembaut** [comment]
up !

**Comment by abirembaut** [comment]
It's been 2 month. Too late !
I merge this as there is no new feedback and if we want to add more content, I suggest opening a new PR.

**Pull request merged**
