### PR TITLE
fix(anchors): Re-inserting anchors and adding links

### PR DESCRIPTION
**Pull request by lcustodio**
A migration on the docs removed multiple links to page anchors across the doc,
this PR aims to put them back in place.

Closes [BS-16698](https://bonitasoft.atlassian.net/browse/BS-16698)

### CODE REVIEW

**Comment by lcustodio** [comment]
test this please

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
Links don't work
Try to put anchor BEFORE the title
Check http://doc.rd.lan:50323/7.3?page=rest-api-overview

**Comment by lcustodio** [comment]
retest this please

**Comment by lcustodio** [comment]
retest this please

**Comment by lcustodio** [comment]
Tests are not working and the generated site doesn't compile. Postponing to next week.

**Pull request closed without merging**
