### PR TITLE
Update uid-case-overview-tutorial.md

### PR DESCRIPTION
**Pull request by valdesfm**
Type fixed (form was used instead of page)

Insert your Pull Request description here...

* add support for ...
* fix ... behaviour
* refactor ....

### CODE REVIEW

**Comment by tbouffard** [comment]
@valdesfm the change looks good 
As the form wording has been introduced in #1023 in the 7.7 branch, it seems that the proposed change should also apply to 7.7+ documentation.
Do you confirm?

**Comment by valdesfm** [comment]
Yes I do. Thanks!

**Comment by tbouffard** [comment]
Ok, R&D will manage the rebase of the PR on the 7.7 branch prior being able to merge it

**Comment by abirembaut** [comment]
PR merged in 7.10 and commit cherry-picked in 7.7 as it was more convenient.

**Pull request merged**
