### PR TITLE
feat(http): clarify HTTP Basic Auth configuration

### PR DESCRIPTION
**Pull request by educhastenier**

### CODE REVIEW

**Review by vbotnari12 — APPROVED** [review]
Ok, after removing passwords from the release note.

**Comment by educhastenier** [comment]
> Ok, after removing passwords from the release note.

@vbotnari12 Do you mean you are ok to keep default password values everywhere BUT in the release notes? Why?

**Comment by vbotnari12** [comment]
> > Ok, after removing passwords from the release note.
> 
> @vbotnari12 Do you mean you are ok to keep default password values everywhere BUT in the release notes? Why?
For the very simple reason that in the release note we put general information and if needed, direct users for details in the documentation. Ideally, there should not be passwords in the documentation (nor install/install), but that's a topic we are not going to address here.

**Review by ugaston — APPROVED** [review]
This is really helpful!!
It looks good for me.

Thanks Manu!

**Pull request merged**
