### PR TITLE
fix(perf-tuning): add useful GC

### PR DESCRIPTION
**Pull request by marielle-spiteri**
* This is the recommendations provided by support team to every customer for an improved GC management

### CODE REVIEW

**Comment by alachambre** [comment]
You did a similar pull request on the 2021.2 branch, is it normal? Even if it is, by opening the two pull requests at the same time you'll have to manage conflicts. 

https://github.com/bonitasoft/bonita-doc/pull/1852/files

**Comment by tbouffard** [comment]
> You did a similar pull request on the 2021.2 branch, is it normal? Even if it is, by opening the two pull requests at the same time you'll have to manage conflicts.
> 
> [#1852 (files)](https://github.com/bonitasoft/bonita-doc/pull/1852/files)

- prior 2021.2, GC settings are provided both Java 8 and 11
- from 2021.2, they should be provided only for java 11, as Bonita doesn't support Java 8 starting from 2021.2

Suggestions: we first merge this PR (#1851), propagate changes from 7.10 upwards, then #1852 will have conflicts. We resolve conflicts and #1852 ensures that GC settings are only provided for Java 11.

**Comment by marielle-spiteri** [comment]
I've closed the #1852, let's merge this one and I'll change the 2021.2 versions after that. Indeed I did 2 PR as 2021.2 doesn't support Java 8 anymore. @tbouffard , I don't understand what you want to do with the other very old PR on the completely other pages about the Studio. I don't even know how these old PR are still open 3 years later. Please kindly clarify what you mean?  #1851 is ready to merge.

**Review by tbouffard — APPROVED** [review]

**Comment by tbouffard** [comment]
> I've closed the #1852, let's merge this one and I'll change the 2021.2 versions after that. Indeed I did 2 PR as 2021.2 doesn't support Java 8 anymore. @tbouffard , I don't understand what you want to do with the other very old PR on the completely other pages about the Studio. I don't even know how these old PR are still open 3 years later. Please kindly clarify what you mean? #1851 is ready to merge.

Sorry @mariellebonita, my comment contained typos: I stated PR `852` instead of `1852` (missing leading 1) so it wasn't targeting the other PR related to this one. I have fixed the comment. 😝

**Pull request merged**
