### PR TITLE
Delete page specify-cpu-cores.md in 7.4

### PR DESCRIPTION
**Pull request by pooravbos**
Removing this page from the documentation as part of cleaning the document of all cpu core based licensing references

### CODE REVIEW

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
Why didn't you do this PR on 7.3, like the previous one?

**Comment by pooravbos** [comment]
This does not exist in 7.3, at least I didn't find this doc in 7.3

**Comment by laurentleseigneur** [comment]
* in 7.3 this information is in https://github.com/bonitasoft/bonita-doc/blob/7.3/md/tomcat-bundle.md and https://github.com/bonitasoft/bonita-doc/blob/7.3/md/jboss-bundle.md
* in 7.4 this information is linked into tomcat-bundle.md  and wildfly-bundle.md, so links are broken, please amend your commit

This suppose to have an additionnal PR for 7.3 version. 

is there a jira issue attached to this change?

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by educhastenier** [comment]
I will merge your 3 PRs into this one

**Pull request merged**
