### PR TITLE
Bs 15891 api customuserinfo definition

### PR DESCRIPTION
**Pull request by pierre-yves-monnet**
BS-15891
Change
/API/customuserinfo/definitions
to 
/API/customuserinfo/definition
(remove the S)

### CODE REVIEW

**Comment by redboul** [comment]
Hello,

ideally, each PR should contain a single commit based on the branch you want to merge to : here, the `BS-15891` commit should be the only one, the `First version` commit is not relevant to this PR.

can you rebase this branch to remove the `First version` commit please ( something like `git rebase -i HEAD~3`, remove the `First version` line and `git push --force`) ?

**Comment by redboul** [comment]
Ok to merge otherwise

**Comment by pierre-yves-monnet** [comment]
yes, strange, I have 2 commit, one named "First version", a second "BS-15891". So, I assume it's OK because the last one is the one expected.

"rebase this branch" ? I tried with tortoise git to "rebase" my branch "BS-15891_API_customeruserinfo"  and my Explorer died. After restarted, I don't see any "Head~3".
Using git rebase -i HEAD~3, it say that I don't have any unstaged changes, please commit or stash.
So, I plan to follow a GIT course on the web to understand this tool, after I will do what you ask.
If during this time someone want to remote the "s" in the page, it will be welcome because at this moment the documentation is wrong.

Thanks for the review

**Comment by redboul** [comment]
`unstaged changes` mean that you have work in progress onto the source files and that automatic modification done with rebase or merge cannot be processed automatically. 
From there, you have 3 choices: 
- commit: to have the changes inside the git history with exact modifications to manage
- stash: put the modification in a temporary stack with `git stash`. You can have them back with `git stash pop`
- reset : reset the current modification of your sources, and lose those modification, to the last commit doing `git reset --hard`  

After that, you willl be able to do a rebase like I said with the command line.

**Pull request closed without merging**
