### PR TITLE
feat(studio install): add Linux blank welcome page troubleshooting

### PR DESCRIPTION
**Pull request by educhastenier**

### CODE REVIEW

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
_Here is what it looks like_:
_________________________
troubleshoot_studio_welcome_page

**Review by alachambre — APPROVED** [review]
Looks good!
I can't test it cause i'm on windows, but it's certainly fine!

**Review by tbouffard — APPROVED** [review]
LGTM, the rendering of the page is ok. So I am merging this PR

**Pull request merged**
