### PR TITLE
tr(asciinema): host our own asciinema files & player

### PR DESCRIPTION
**Pull request by educhastenier**
Relates to [BR-394](https://bonitasoft.atlassian.net/browse/BR-394)

### CODE REVIEW

**Comment by educhastenier** [comment]
:warning: display can be checked here:
https://cidoc.cloud.bonitasoft.com:21204/bonita/7.8/migrate-from-an-earlier-version-of-bonita-bpm#update-case-overview-pages
 Enjoy

**Comment by educhastenier** [comment]
It looks like:
image

**Comment by JeremJR** [comment]
@educhastenier why don't you use asciinema-player.js and css already available into bonita-doc-site assets ?
It avoids to duplicate this into each branches of each app (bonita, bcd...)
https://github.com/bonitasoft/bonita-doc-site/pull/108/files
https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/130/files#diff-922a3f401a6f1a4777be1c61d13c0a8cR27
https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/130/files#diff-922a3f401a6f1a4777be1c61d13c0a8cR30

**Comment by educhastenier** [comment]
> @educhastenier why don't you use asciinema-player.js and css already available into bonita-doc-site assets ?
> It avoids to duplicate this into each branches of each app (bonita, bcd...)
> https://github.com/bonitasoft/bonita-doc-site/pull/108/files
> https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/130/files#diff-922a3f401a6f1a4777be1c61d13c0a8cR27
> https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/130/files#diff-922a3f401a6f1a4777be1c61d13c0a8cR30

@JeremJR Just because I didn't know that ! :-) Thx. Good catch :+1: I fixed it.

**Pull request merged**
