### PR TITLE
fix (doc): add candidate and assignee in actors.md

### PR DESCRIPTION
**Pull request by dcoille**
Add candidate and assignee paragraph to actors.md

### CODE REVIEW

**Comment by alachambre** [comment]
Hi Delphine, 

This pull request is way to big, are you sure that 7.7 is the base branch?

**Comment by dcoille** [comment]
Hi Adrien,
I think I have made a mistake when pushing it, because I just wanted to push the file I have updated (actors.md) with the new chapter.
I think 7.7 is the correct branch if we consider 7.7. is the base branch and then a "moulinette" will update 7.8 until 7.11 (as Benjamin told me)?

**Comment by educhastenier** [comment]
> Hi Adrien,
> I think I have made a mistake when pushing it, because I just wanted to push the file I have updated (actors.md) with the new chapter.

Yes, @dcoille do you want to rework it with me in pair-prg?

> I think 7.7 is the correct branch if we consider 7.7. is the base branch and then a "moulinette" will update 7.8 until 7.11 (as Benjamin told me)?

7.8 is the first supported version. You should rebase your contribution on 7.8

**Comment by dcoille** [comment]
@educhastenier sure, with pleasure! Will be a nice work to do for me.

**Comment by educhastenier** [comment]
redone on another PR

**Pull request closed without merging**
