### PR TITLE
fix(taxo): fix license dead link

### PR DESCRIPTION
**Pull request by NathalieC**
* change license info in licenses

### CODE REVIEW

**Review by pabloalonso — APPROVED** [review]
LGTM

**Comment by tbouffard** [comment]
@NathalieC the broken link also exists in older version, for instance 7.9

**Comment by NathalieC** [comment]
ok will fix it there too. thx

**Comment by tbouffard** [comment]
hm, I was rechecking and finally, I only saw the issue in 2021.1 and 2021.2 in taxonomy.
Sorry for disturbing 😸

**Comment by NathalieC** [comment]
ok

**Pull request merged**
