### PR TITLE
chore(7.11): Put 7.11 out of support

### PR DESCRIPTION
**Pull request by benjaminParisel**
* this version is now out-of-support, we want to display these information and remove the possibilty to update the content
* Remove build action on this deprecated version

### CODE REVIEW

**Comment by tbouffard** [comment]
Based on discussion between @NathalieC and @benjaminParisel, this PR won't be merged prior next Friday.
Putting it to draft to avoid merge by mistake.

**Review by tbouffard — APPROVED** [review]
✔️ LGTM, follow requirements described in https://github.com/bonitasoft/bonita-documentation-site/blob/master/docs/documentation-components-and-versions.adoc#mark-version-as-out-of-support

**Comment by educhastenier** [comment]
@benjaminParisel Why did you deleted all those files?

**Comment by benjaminParisel** [comment]
@educhastenier You can find your answer in the document link in the comment from Thomas

**Pull request merged**
