### PR TITLE
doc(migration): REST API Extensions not migrated

### PR DESCRIPTION
**Pull request by marielle-spiteri**
* REST API Extensions not migrated automatically

### CODE REVIEW

**Review by ugaston — APPROVED** [review]
Definitely! Mandatory to remind users REST APIs are customisations, so not migrated per se.

Looks good to me.

Cheers!

**Comment by tnguyen1** [comment]
retest this please

**Comment by tbouffard** [comment]
@mariellebonita does this apply only to the 7.5 documentation version?
I need this information to know before merging in the right branch

**Comment by marielle-spiteri** [comment]
@tbouffard , it applie to the REEST API extension migration since the beginning of the existence of rest API extension, so I'd say since 7.0

**Comment by tbouffard** [comment]
Ok so I am going to change the base branch to 7.3 prior to merge

**Comment by tbouffard** [comment]
@mariellebonita I have rebased your work on the 7.3 branch and reword the sentence to match what we had in the 7.3 documentation.
If ok for you, I can merge this PR

**Comment by marielle-spiteri** [comment]
@tbouffard yes that's fine, you can merge, thanks!

**Pull request merged**
