### PR TITLE
update(product versioning): element and table

### PR DESCRIPTION
**Pull request by NathalieC**
* change table data from 2021.2 to 2022.1

### CODE REVIEW

**Comment by tbouffard** [comment]
@NathalieC the build of the site preview is in error because a page in the 2021.2 branch (so the branch of the later versions as well) contains a duplicated block id. This will be fixed by #2033

**Comment by educhastenier** [comment]
> @NathalieC the build of the site preview is in error because a page in the 2021.2 branch (so the branch of the later versions as well) contains a duplicated block id. This will be fixed by #2033

✅ Fixed and rebased

**Review by tbouffard — COMMENTED** [review]
✔️ the table data renders correctly

image

**Review by tbouffard — CHANGES_REQUESTED** [review]
@NathalieC mentioned me privately that the `artifact` to `element` renaming should also applied to `2021.2`.
So this PR must be amended to remove the renaming here, and a new PR targeting `2021.2` with the related changes must be created (see #2307)

**Review by tbouffard — APPROVED** [review]
LGTM, the renaming has been removed

**Pull request merged**
