### PR TITLE
docs(web): Fix errors in the Getting Started (2021.2)

### PR DESCRIPTION
**Pull request by mbource**
Fix errors in the Getting Started tutorial. 

Here's a report of what I changed in the PR :
- In https://documentation.bonitasoft.com/bonita/2021.2/getting-started/draw-bpmn-diagram ->  Dead link: https://www.bonitasoft.com/library/ultimate-guide-bpmn , I change it with the one working. 

- In https://documentation.bonitasoft.com/bonita/2021.2/getting-started/define-business-data-model ->  Step 9 : Finish button don’t exist in the UI. I do believe it’s supposed to say “Deploy” because first time I didnt deploy the BDM and I couldn’t use the application with the business data. It can be confusing. 

- In https://documentation.bonitasoft.com/bonita/2021.2/getting-started/define-who-can-do-what , end of article, the sentence “Run the process again, and this time only mauro.zetticci should have access to Read the answer and rate it” is wrong. This is not the task Read the answer and rate it but Review and answer claim who should be mark on the doc.

### CODE REVIEW

**Comment by NathalieC** [comment]
Thanks for these useful changes.
A few more suggestions.
- In the page Define a Business Model, in step 2, the "Add" button is actually an "Add Object" button to click
- In step 4, "Attributes" is not quite a tab but rather a "table"
- After the last note, in "Now you have a fully functional business data management model." This is actually "Now you have a fully functional business data model." No need of "management".

**Review by NathalieC — APPROVED** [review]

**Review by tbouffard — CHANGES_REQUESTED** [review]
See https://github.com/bonitasoft/bonita-doc/pull/1998#issuecomment-1072318004

**Comment by mbource** [comment]
Because all those fix are already in the https://github.com/bonitasoft/bonita-doc/pull/1998 PR, I think this PR should be closed and not merged.

**Comment by tbouffard** [comment]
> Because all those fix are already in the #1998 PR, I think this PR should be closed and not merged.

I agree, #1998 targets v2021.1 so everything will be merged in 2022.2 once merged.

**Pull request closed without merging**
