### PR TITLE
docs(Tomcat bundle): change the troubleshooting section format

### PR DESCRIPTION
**Pull request by amrzwail**
Versions: 2021.2, 2022.1, 2022.2

Changing the format of the troubleshooting section.

### CODE REVIEW

**Comment by vbotnari12** [comment]
Amr, please sign the Contributor License Agreement, else it will not be possible to merge the PR. Thanks.

**Review by vbotnari12 — APPROVED** [review]
ok for the content. Pending license signature for PR merge.

**Review by educhastenier — CHANGES_REQUESTED** [review]
Hi @amrzwail ,

Thx for this valuable contribution.
One remark though: as you state in the text, the first version to require Java 11 only is the 2021.2. Hence, can you rebase this PR on the 2021.2 branch?

**Comment by vbotnari12** [comment]
> Hi @amrzwail ,
> 
> Thx for this valuable contribution. One remark though: as you state in the text, the first version to require Java 11 only is the 2021.2. Hence, can you rebase this PR on the 2021.2 branch?

=> change done, but there are conflicts now...

**Comment by tbouffard** [comment]
@vbotnari12 rebase done onto the `2021.2` branch
@educhastenier can you please review again? thanks

**Comment by tbouffard** [comment]
⚠️ the troubleshooting section looks weird

image

**Comment by tbouffard** [comment]
@educhastenier can you please review again? thanks

**Comment by tbouffard** [comment]
@cvidaillac are you sure you wanted to close this PR? If so, please leave a comment to shortly explain why.

**Comment by cvidaillac** [comment]
Wrong action. sorry

**Comment by educhastenier** [comment]
> @educhastenier can you please review again? thanks

Sorry, I don't receive updates on PR. Looking right now.

**Review by educhastenier — APPROVED** [review]

**Comment by educhastenier** [comment]
Thx @amrzwail for this contribution

**Pull request merged**
