### PR TITLE
fix(format): fix wrong italic+bold asciidoc conversion

### PR DESCRIPTION
**Pull request by educhastenier**

### CODE REVIEW

**Comment by educhastenier** [comment]
### Before
image

### After
image

**Comment by tbouffard** [comment]
@educhastenier this looks pretty good, I will review it in details later.
I have marked this PR as 'Do not merge' as we have a demo on next Tuesday, and we would like to fix one of the page (Studio Preferences) as an example to explain how to contribute: we plan to exactly fix the italic+bold issue, so we need the site to have the problem, otherwise there won't be anything to fix with a contribution 😸 . The PR will be something like #1518.
So, we suggest to merge this PR after the demo.

**Comment by alachambre** [comment]
Sorry for the demo divulgaching !

**Comment by educhastenier** [comment]
Rebased ✔️

**Pull request merged**
