### PR TITLE
Update multi-tenancy-and-tenant-configuration.adoc

### PR DESCRIPTION
**Pull request by vbotnari12**
As multi-tenancy is deprecated at Bonita, it should be reflected in the documentation.

### CODE REVIEW

**Review by tbouffard — CHANGES_REQUESTED** [review]
⚠️ Please close this Pull Request
A Pull Request targeting the Bonita 7.10 documentation already exists (#1848). Once merged into 7.10, changes will be propagated to all subsequent Bonita versions (7.11 to 2022.1).

**Comment by vbotnari12** [comment]
> ⚠️ Please close this Pull Request A Pull Request targeting the Bonita 7.10 documentation already exists (#1848). Once merged into 7.10, changes will be propagated to all subsequent Bonita versions (7.11 to 2022.1).

It should not be like this. documentation for version 7.10 and 7.11 are the same and documentation for 2021.1 and 2021.2 should be the same, so no, the changes from 7.10 should NOT be propagated to other version than 7.11. Possible?

**Comment by alachambre** [comment]
@vbotnari12 this is not how it works. 

You first make a pull request on the branch 7.10, it is propagated to all younger version (7.11, 2021.1, 2021.2).
Then if a different content is expected on the 2021.1 version and above you make a second contribution on the branch 2021.1. This second contribution will be propagated on the 2021.2. 

This is how Git works.

**Comment by vbotnari12** [comment]
As the PR #1848 for version 7.10 will be applied, this PR is useless. Checked with Thomas.

**Pull request closed without merging**
