### PR TITLE
docs(uid_variables): Call a Rest API on a condition

### PR DESCRIPTION
**Pull request by jeromecambon**
Covers [UID-715](https://bonitasoft.atlassian.net/browse/UID-715)

### CODE REVIEW

**Review by pabloalonso — COMMENTED** [review]
If we do it in this way, there will be an issue as the REST API permissions will not be set. This may require a second action to update the file page.properties which is not native in UID.

The other way is to do this way:
../API/bpm/userTask/{{callTask}}
This will trigger the call anyway with 'undefined' probably (to double check)

**Comment by pabloalonso** [comment]
NOTE: In addition another use case that we need to cover is how to autorefresh the call with a t={{timestamp}}

**Comment by jeromecambon** [comment]
> If we do it in this way, there will be an issue as the REST API permissions will not be set. This may require a second action to update the file page.properties which is not native in UID.
> 
> The other way is to do this way: ../API/bpm/userTask/{{callTask}} This will trigger the call anyway with 'undefined' probably (to double check)

Good catch!
The latest is ok. An External API variable does not trigger a call in case of undefined variable in the URL.

**Comment by jeromecambon** [comment]
> 

I suggest to handle this in a separate PR. Can you create a Jira for this?

**Comment by jeromecambon** [comment]
> 

I suggest to handle this in a separate PR. Can you create a Jira for this?

**Comment by jeromecambon** [comment]
> NOTE: In addition another use case that we need to cover is how to autorefresh the call with a t={{timestamp}}

I suggest to handle this in a separate PR. Can you create a Jira for this?

**Comment by pabloalonso** [comment]
LGTM

**Review by pabloalonso — APPROVED** [review]

**Pull request merged**
