### PR TITLE
feat(subtasks): remove documentation on subtasks

### PR DESCRIPTION
**Pull request by baptistemesta**
this feature do not exists anymore starting from 7.3
I think it is safe to remove now

### CODE REVIEW

**Comment by NathalieC** [comment]
ok to remove those. We need to make sure we still mention the fact that even if we don't provide the subtask creation feature after 7.3, we continue to execute subtasks if they have been created before 7.3.

**Comment by baptistemesta** [comment]
I think it was the purpose of the page. We can keep it if we still need to mention that in 7.9

**Comment by tbouffard** [comment]
Congrats @baptistemesta for PR number 1000
:clap:

**Comment by educhastenier** [comment]
:question: so, do we remove the whole page or not ?

**Comment by NathalieC** [comment]
So. It is ok to remove the page on subtasks. You are right. 
Here is the condition I'd like to see fulfilled: the note at the end of the "user-task-list" should say: 
"Since Bonita 7.3.0, creating subtasks is no longer possible. However, if subtasks have been created in a process instance in an old Bonita version, and if the Bonita Platform has been migrated to a later version while the case was open, then the subtasks will still be visible to the users assigned, and users will still be able to complete them."

**Comment by educhastenier** [comment]
> So. It is ok to remove the page on subtasks. You are right.
> Here is the condition I'd like to see fulfilled: the note at the end of the "user-task-list" should say:
> "Since Bonita 7.3.0, creating subtasks is no longer possible. However, if subtasks have been created in a process instance in an old Bonita version, and if the Bonita Platform has been migrated to a later version while the case was open, then the subtasks will still be visible to the users assigned, and users will still be able to complete them."

I handle this !

**Pull request merged**
