### PR TITLE
docs: correct all notes for subscription editions

### PR DESCRIPTION
**Pull request by marcobonita**
* Use *Subscription editions* instead *Enterprise, Performance, and Efficiency editions*
* Updated download links and all subscription editions description

### CODE REVIEW

**Comment by educhastenier** [comment]
@marcobonita See above for a few things to fix on this PR. Thx.

**Comment by marcobonita** [comment]
> @marcobonita See above for a few things to fix on this PR. Thx.

Thanks @educhastenier , I made the changes

**Comment by marcobonita** [comment]
Removing state label

**Review by benjaminParisel — APPROVED** [review]
LGTM ! Happy to see the wording of editions are now easy to use :clap:

**Pull request merged**
