### PR TITLE
docs(mssql): add Kerberos authentication

### PR DESCRIPTION
**Pull request by gleclerre**
Add paragraph about Kerberos authentication for MSSQL database

### CODE REVIEW

**Review by rbioteau — COMMENTED** [review]
Does it only applies to the 2023.2 version specifically ?

**Comment by techosbonitasoft** [comment]
> Does it only applies to the 2023.2 version specifically ?

No. I've encountered this problem with this version, but I assume it's the same with previous versions (probably since 7.9.0, according to the configuration file).

**Comment by educhastenier** [comment]
> > Does it only applies to the 2023.2 version specifically ?
> 
> No. I've encountered this problem with this version, but I assume it's the same with previous versions (probably since 7.9.0, according to the configuration file).

so you should rebase this PR on 2022.1 (oldest supported version).

Also, @techosbonitasoft you PR cannot be merged until you accept the CLAs...

**Comment by gleclerre** [comment]
CLA signed

Guillaume Leclerre
Technical Consultant
[image: Logo] <https://bonitasoft.com/>
1 place Paul Verlaine
92100 Boulogne Billancourt
<https://www.bonitasoft.com/news/bonitasoft-earns-trustradius-top-rated-2023-award?utm_source=Sigilium&utm_medium=Signature+mail&utm_campaign=2023-TopRated>
<https://www.bonitasoft.com/news/bonitasoft-is-positioned-as-technology-leader-in-2023-spark-matrix-for-dpa-software?utm_source=sigilium&utm_medium=email&utm_campaign=spark-matrix-2023>
[image: Linkedin] <https://www.linkedin.com/company/bonitasoft/>
[image: Twitter] <https://twitter.com/bonitasoft>
[image: Facebook] <https://www.facebook.com/bonitasoftbpm>
[image: Youtube] <https://www.youtube.com/user/BonitaSoft>

[image: Click to know more]
<https://data.sigilium.com/signatures/rce7tmfmuljocwpai2kkf85pv5ykmrc/redirect_link>

**Comment by techosbonitasoft** [comment]
@guillaume
For doc PRs you can still use your account, the repo is public


Pablo ALONSO DE LINAJE
Software Development Manager
[image: Logo] <https://bonitasoft.com/>
32 rue Gustave Eiffel, 38000 Grenoble
<https://www.bonitasoft.com/news/bonitasoft-earns-trustradius-top-rated-2023-award?utm_source=Sigilium&utm_medium=Signature+mail&utm_campaign=2023-TopRated>
<https://www.bonitasoft.com/news/bonitasoft-is-positioned-as-technology-leader-in-2023-spark-matrix-for-dpa-software?utm_source=sigilium&utm_medium=email&utm_campaign=spark-matrix-2023>
[image: Linkedin] <http://www.linkedin.com/in/palonsolinaje>
[image: Twitter] <https://twitter.com/bonitasoft>
[image: Facebook] <https://www.facebook.com/bonitasoftbpm>
[image: Youtube] <https://www.youtube.com/user/BonitaSoft>

[image: Click to know more]
<https://data.sigilium.com/signatures/rcXHwdiePdIYVP1vOKesI2yfT82oorc/redirect_link>

**Review by educhastenier — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
