### PR TITLE
docs(purge-tool): update release notes

### PR DESCRIPTION
**Pull request by educhastenier**
Also, add the RN for the version 1.0.7 that was missing

### CODE REVIEW

**Comment by educhastenier** [comment]
@cvidaillac can you review this PR please?

**Comment by cvidaillac** [comment]
@educhastenier 2 comments from Support team:
1) We would like to keep historical changes done on the tool by adding fixes done on 1.0.4, 1.0.5, 1.0.6 and 1.0.7 versions.
I can help if you can tell me how I can see the fix details somewhere.
2) Regarding what it has been written for 1.0.8, it would be better to keep same format than other change logs done with a Fixes section and Other section.

**Comment by educhastenier** [comment]
> 1. We would like to keep historical changes done on the tool by adding fixes done on 1.0.4, 1.0.5, 1.0.6 and 1.0.7 versions.
>    I can help if you can tell me how I can see the fix details somewhere.

Do you mean you prefer to keep all versions in the RN, even if the binaries of old versions are removed from download?

**Review by cvidaillac — APPROVED** [review]
I'm fine with this version.
Keeping a list of features or bugs through different versions we delieverd is interesting.
Note that some customer may use old version and getting the all changes log list for every versions could make sense. Thanks

**Pull request merged**
