### PR TITLE
fix(engine http client): add a warning about client/server versions

### PR DESCRIPTION
**Pull request by tbouffard**
Covers [BS-17624](https://bonitasoft.atlassian.net/browse/BS-17624)

### CODE REVIEW

**Review by jjargot — COMMENTED** [review]
I clicked on Review changes green button, is this ok?

Thank you for this documentation update.

Is it ok to add also this explanation:
"Keep in mind that after a migration, the bonita client library version used with the java application won't be aligned anymore with the new bonita engine version: plan post migration tests and possibly re compile the application."

These "post migration issues" won't occur with the HTTP REST API, no? if yes, we should recommends strongly to use REST API instead of the java API, in order to get rid of these post migration issues.

I think the migration page should also contain a new step: "if applicable, test external applications using old version of the bonita java client library, and possibly recompile using the new bonita java client library version." https://documentation.bonitasoft.com/bonita/7.6/migrate-from-an-earlier-version-of-bonita-bpm

**Comment by tbouffard** [comment]
As decided with @jjargot I am going to add a note in the migration documentation page about upgrading the version of the client library in 3rd party applications

**Comment by tbouffard** [comment]
@jjargot I have made a change in the migration page

**Review by jjargot — APPROVED** [review]
perfect for me

**Pull request merged**
