### PR TITLE
Explain more explicitly that a BDM can be configured per tenant

### PR DESCRIPTION
**Pull request by philippelaumay**

### CODE REVIEW

**Comment by tbouffard** [comment]
retest this please

**Comment by tbouffard** [comment]
@philippebonita should this doc modification apply to older versions (7.3+)?

**Comment by philippelaumay** [comment]
yes it should apply to older version 7.3+

**Comment by educhastenier** [comment]
test this please

**Comment by educhastenier** [comment]
Looks good to me :+1:

**Pull request merged**
