### PR TITLE
feat(UiPath): add missing documentation page

### PR DESCRIPTION
**Pull request by laurentleseigneur**
* add taxonomy entry
* add single page for UiPath connectors

### CODE REVIEW

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by benjaminParisel** [comment]
retest this please

**Comment by laurentleseigneur** [comment]
retest this please

**Comment by benjaminParisel** [comment]
LGTM

**Review by benjaminParisel — APPROVED** [review]

**Pull request merged**
