### PR TITLE
Update(install-cluster): rename FAQ to Troubleshooting

### PR DESCRIPTION
**Pull request by marielle-spiteri**
* Standardize Troubleshooting section
* To be pushed up to latest verstion

### CODE REVIEW

**Comment by tbouffard** [comment]
⚠️ The 7.9 version is not updated anymore, this Pull Request should target the 7.10 branch

**Comment by marielle-spiteri** [comment]
@tbouffard I created this PR on August 26 when the 7.9 was still editable. I don't know how to rebase, could you do it? If not, I'll create a new PR on 7.10. Thanks!

**Comment by tbouffard** [comment]
@mariellebonita Rebase done with `git rebase --onto=origin/7.10 d0f4c501c0a1f0eb04d9bb512296c2ec08b0ae16`.
The latest argument of the command is the latest commit sha coming from the 7.9 branch prior the rebase. This lets git retrieve all commits from your branch and put them on top of the 7.10 branch.
I have also updated the targeted branch of this PR.

**Comment by NathalieC** [comment]
LGTM

**Pull request merged**
