### PR TITLE
(fix): remove extra ";"

### PR DESCRIPTION
**Pull request by laurentleseigneur**
following @tbouffard advise

### CODE REVIEW

**Review by tbouffard — CHANGES_REQUESTED** [review]
The issue exist in other pages and starting from Bonita 7.11, so the fix should target this version.
The proposed fixed changes the rendered schemaLocation: we should see a space

**Comment by educhastenier** [comment]
I do not see any `;` change in this PR 🤔

**Comment by tbouffard** [comment]
@educhastenier the internal reference for the issue is [RUNTIME-969](https://bonitasoft.atlassian.net/browse/RUNTIME-969). It provides more details about the problem and the result of a quick investigation.

**Comment by laurentleseigneur** [comment]
rebased PR on 7.11 branch as requested by @tbouffard

**Comment by tbouffard** [comment]
The rebase on 7.11 is ok, but the fix is not accurate. 
There are also other pages impacted by the issue, see [RUNTIME-969](https://bonitasoft.atlassian.net/browse/RUNTIME-969)

**Comment by laurentleseigneur** [comment]
seems i didn't get the way to fix it by removing the `` in XSD section ?

**Pull request closed without merging**
