### PR TITLE
fix(naming): remove references to Bonita BPM

### PR DESCRIPTION
**Pull request by tbouffard**
Bonita BPM product name references have been introduced during older
documentation version updates propagation.

### CODE REVIEW

**Comment by NathalieC** [comment]
In single-sign-on-with-cas.md, some references to BonitaBPM remain in folders names.
eg.: BonitaBPMSubscription-x.y.z-deploy
(We have found them with Ctrl+F).
Can you also remove them?

**Comment by educhastenier** [comment]
retest this please

**Comment by tbouffard** [comment]
@NathalieC yes I'll do it. I had only searched for `Bonita BPM`

**Comment by amottier** [comment]
LGTM

**Pull request merged**
